# Sandbox (S&Box) Pterodactyl Egg
# Copyright (c) 2026 Steven A. Smith
#
# Single-stage runtime image using steamcmd/steamcmd:alpine.
#
# Build from the repo root:
#   docker build --platform linux/amd64 \
#     -f Yolk/DockerFile \
#     -t GameForgeGG/sbox-egg:latest \
#     .

FROM steamcmd/steamcmd:alpine

LABEL author="Steven A. Smith" maintainer="team@gameforge.gg"
LABEL description="s&box Pterodactyl Egg" version="2.2" license="MIT"
LABEL org.opencontainers.image.authors="Steven A. Smith" \
      org.opencontainers.image.description="s&box Game Server Egg" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.source="https://github.com/GameForgeGG/sbox-egg"

ARG PUID=999
ARG PGID=999

# Runtime defaults
ENV CONTAINER_HOME=/home/container \
    HOME=/home/container \
    WINEPREFIX=/home/container/.wine \
    WINEARCH=win64 \
    WINEDEBUG=-all \
    WINEDLLOVERRIDES=icu,icuuc=d \
    SBOX_APP_ID=1892930 \
    SBOX_INSTALL_DIR=/home/container/sbox \
    SBOX_SERVER_EXE=/home/container/sbox/sbox-server.exe \
    SBOX_AUTO_UPDATE=1 \
    SBOX_LOG_KEEP=10 \
    STEAM_PLATFORM=windows \
    DOTNET_EnableWriteXorExecute=0 \
    DOTNET_TieredCompilation=0 \
    DOTNET_ReadyToRun=0 \
    DOTNET_ZapDisable=1 \
    GAME= \
    MAP= \
    SERVER_NAME= \
    SBOX_PROJECT= \
    SBOX_EXTRA_ARGS= \
    RUNTIME_MODE=wine \
    XDG_RUNTIME_DIR=/tmp

RUN apk add --no-cache \
                bash \
                ca-certificates \
                gnutls \
                libgcc \
                libstdc++ \
                tar \
                wget \
                wine

RUN mkdir -p \
        /home/container/.wine \
        /home/container/.local/share \
         /home/container/projects \
         /home/container/logs \
         /home/container/sbox \
    && chmod 1777 /tmp

COPY Yolk/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/entrypoint.sh \
    && chmod 0755 /usr/local/bin/entrypoint.sh

WORKDIR ${CONTAINER_HOME}

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["start-sbox"]